baseURL = 'https://ran-n.github.io/titoriais/'
languageCode = 'en'
title = 'Titoriais'
theme = 'hugo-theme-monochrome'
defaultContentLanguage = "gz"
enableEmoji = true
#contentDir = 'content'
custom_js = ["js/custom.js"]
#relativeURLs = true
canonifyURLs = true

googleAnalytics = "G-EDFGMBGH74"

[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.highlight]
codeFences = false
lineNos = false
