navbar_title = "Titorais"
footer = "Titoriais ❤️"
author = "Ran#"

enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true

enable_site_search = true
enable_math = true
enable_zooming_js = true

enable_open_graph = true
enable_twitter_cards = true

[params.list_layout]
enable_group_by_year = false
enable_show_date = false
enable_pagination = false

[param.syntax_highlight]
lig = "builtin"
    [param.syntax_highlight.builtin]
    enable_code_copy = true
